lsst/ip_diffim

tests/testDipole.py

This is required as of Numpy 1.12.

Review for DM-9316: tests broken with NumPy 1.12

---

python/lsst/ip/diffim/dipoleFitTask.py

Simple ticket to extend `timeMethod` to more Tasks.

DM-7268: Record source measurement time in the metada

---

doc/.gitignore
doc/conf.py
doc/index.rst
doc/ip_diffim/index.rst
doc/lsst.ip.diffim/index.rst
doc/manifest.yaml

No real changes, and `automodapi` is commented out.

Add Sphinx support

---

python/lsst/ip/diffim/dcrModel.py
tests/test_dcrModel.py

This simpler data model reduces execution time by a factor of ~3.

DM-17564: Convert DcrModel to image type from maskedImage

---

python/lsst/ip/diffim/metrics.py
tests/test_metrics.py

This PR changes source count metrics to take single inputs, following support for non-aggregating metrics in lsst/verify#54.

DM-20974: Remove aggregation support/requirement from MetricTask

---

python/lsst/ip/diffim/metrics.py

This PR updates concrete `MetricTask`s to take advantage of the changes added in lsst/verify#63.

DM-21911: Retrofit Gen 3 functionality onto MetricTask

---

python/lsst/ip/diffim/imagePsfMatch.py

DM-23277 Update ImageDifferenceTask to remove v20 deprecation warnings

---

python/lsst/ip/diffim/zogy.py
tests/test_pixelOffset.py

Fix one-pixel offset for ZOGY.
Duplicate of #147 
But this PR is from a branch named after the ticket so it will be automatically linked from JIRA.

DM-11990: Fix one-pixel offset for ZOGY.

---

python/lsst/ip/diffim/metrics.py

This PR fixes all `ip_diffim` metric tasks to have valid input connections.

DM-21919: Run ap_verify end-to-end in Gen 3

---

python/lsst/ip/diffim/diffimTools.py

remove mathLib

---

doc/lsst.ip.diffim/tasks/lsst.ip.diffim.metrics.FractionDiaSourcesToSciSourcesMetricTask.rst
doc/lsst.ip.diffim/tasks/lsst.ip.diffim.metrics.NumberSciSourcesMetricTask.rst
python/lsst/ip/diffim/metrics.py

This PR fixes some documentation errors found in older metrics while working on DM-27032.

DM-27032: Create deblended source metric

---

python/lsst/ip/diffim/makeKernelBasisList.py

This PR enables an option to pass `basisSigGauss` - the size parameter of the basis function to `makeKernelBasisList` function at run time instead of looking up the frozen values from the config. This allows to control the kernel parametrization during PSF Gaussianization stage for GAaP fluxes/colors. This has to be at runtime and not passed as a config parameter because the size depends on the seeing at the location of each source.

DM-28955: Allow passing `basisSigGauss` parameter to `makeKernelBasisList`

---

python/lsst/ip/diffim/getTemplate.py

Previously it was loading the PSFs pre-warped to the detector WCS.
CoaddPsf warps when evaluating anyway so pre-warping is overkill
and harder to debug.

DM-31777-v23: Build CoaddPsf of CoaddPsfs in tract WCS

---

README.rst
doc/conf.py
setup.cfg

Updates based on the latest updates in the package template (https://github.com/lsst/templates/tree/master/project_templates/stack_package)
- Add a basic README
- Update conf.py for the documenteer 0.6 Sphinx configuration API

DM-30015: Update conf.py for documenteer 0.6

---

python/lsst/ip/diffim/modelPsfMatch.py

Fixes some deprecation warnings, and potential bugs.

DM-32549: Supply position to psf.computeShape() calls

---

python/lsst/ip/diffim/subtractImages.py

This PR copies the similar code from `pipe_tasks.ImageDifferenceTask`.

DM-35654: Add finalized PSF support to the new image differencing task

---

python/lsst/ip/diffim/diffimTools.py
python/lsst/ip/diffim/dipoleFitTask.py
python/lsst/ip/diffim/dipoleMeasurement.py
python/lsst/ip/diffim/imageDecorrelation.py
python/lsst/ip/diffim/imageMapReduce.py
python/lsst/ip/diffim/imagePsfMatch.py
python/lsst/ip/diffim/kernelCandidateQa.py
python/lsst/ip/diffim/makeKernel.py
python/lsst/ip/diffim/psfMatch.py
python/lsst/ip/diffim/utils.py
python/lsst/ip/diffim/zogy.py
tests/test_basisLists.py
tests/test_dipole.py
tests/test_imageDecorrelation.py
tests/test_imageMapReduce.py
tests/test_imageStatistics.py
tests/test_kernelCandidateAndSolution.py
tests/test_kernelCandidateDetection.py
tests/test_pixelOffset.py
tests/test_zogy.py

Also fixes a major bug in the dipole calculation that was due to the old API.

DM-39173: Update the API for accessing the image, mask, and variance planes

---

python/lsst/ip/diffim/imageDecorrelation.py
python/lsst/ip/diffim/utils.py

If the simple PSF image calculation fails during image decorrelation, compute an average PSF across the template. Note that this will only be used if the science image is convolved during A&L image differencing.

DM-40194: Add fallback for gaps in the template PSF in decorrelation.

---

python/lsst/ip/diffim/subtractImages.py

DM-40669: Create a new INJECTED_CORE mask plane

 DM-40669: Create a new INJECTED_CORE mask plane

---

python/lsst/ip/diffim/detectAndMeasure.py
python/lsst/ip/diffim/subtractImages.py

Revert "DM-41118: add diffim QA metrics"

---

python/lsst/ip/diffim/detectAndMeasure.py
tests/test_detectAndMeasure.py

This reverts commit 9621bc498494605728924345eb7a96be6ad82af0, reversing changes made to db0af172c8922bf53623a929588890e18ca74e87.

Revert "Merge pull request #316 from lsst/tickets/DM-44319"

---

python/lsst/ip/diffim/dipoleFitTask.py

Add CCW from +x to schema field documentation for `dipoleFit_orientation`
Passes Jenkins through `ci_ap`

DM-44410: Clarify dipole orientation convention.

---

python/lsst/ip/diffim/subtractImages.py

One removal was missed in the previous implementation ticket

DM-46135: Remove deprecated keyword
